source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target "SKPhotoBrowserExample" do
    pod 'SDWebImage'
end
